// File main.cpp

/*****************************************************************
	Programmer: Matthew Sherwood, Li Zhang, Juan Hernandez       *
	Class: CSCE 4600                                             *
	Date: 04/27/2015                                             *
	Assignment: Project 2                                        *
	Purpose: To  simulate of different scheduling disciplines to *
             allocate set of processes to available processors   *
*****************************************************************/

#include "processes.h"
#include "processor.h"
#include <string>
#include <chrono>
#include <fstream>

#define clear() cout<<"\033[H\033[J"

void processOutput(c_Proc** ,int);
void simulationOutput(float, double, int, int);
void sortProcs(c_Proc**);
void userPrompt(int*, int*);
void welcomeMsg();
void endMsg();
extern bool simulator(c_Proc**, int, int,  float &memCount);
extern void processorOutput();

/** @brief           Writes process info to processes.txt
 *
 *  @details         Writes the process info after being sorted
 *                   from least to greatest
 *
 *  @param process[] An array of all the processes.
 *  @param numJobs   Total amount of processes
 */
void processOutput(c_Proc** process, int numJobs){
	//Clears the processes.txt file just in case
	//"make clean" has not been run
	process[0]->f.open("processes.txt");
	process[0]->fileOutput();

	//Writes process info to processes.txt
	for(int i=0; i<numJobs; ++i){
		process[i]->f.open("processes.txt",ios::app);// the output file
		process[i]->fileOutput();
		process[i]->f.close();
	}
}

/** @brief           Writes total time and memory consumption to data.txt
 *
 *  @details         Writes how many processes were created, how many
 *                   processors were created, and the total time and
 *                   memory consumption to run all processes
 *
 *  @param memory    Total amount of memory
 *  @param time      Total time to run all processes
 *  @param numJobs   Total amount of processes
 *  @param procNum   Total amount of processors
 */
void simulationOutput(float memory, double time, int numJobs, int numProcs){
	ofstream s;
	//Opens the data.txt file
	s.open("data.txt",ios::app);
	s<<"Total amount of jobs:"<<numJobs<<endl;
	s<<"Total amount of processors"<<numProcs<<endl;
	s<<"Total run time:"<<time<<endl;
	s<<"Total memory consumption:"<<memory<<endl;
	s<<"\n"<<endl;
	s.close();
}

/** @brief           Bubble sort algorithm implementation
*
*   @details         Sorts according to exponent first and then base
*                    while the exponent is the same
*
*   @param process[] Array of processes
*/
void sortProcs(c_Proc** process, int numJobs){
	//Creates a temporary process to use when switching process
	c_Proc* temp = new c_Proc(0);

	//Sort process from least to greatest based on the exponent
	for (int i=numJobs-1; i>= 0; i--){
		for (int j = 1; j <= i; j++){
			if (process[j-1]->exponent > process[j]->exponent){
				temp = process[j-1];
				process[j-1] = process[j];
				process[j] = temp;
			}
		}
	}
	//Sort process from least to greatest based on the base when
	//the exponent is the same
	for (int i=numJobs-1; i>= 0; i--){
		for (int j = 1; j <= i; j++){
			if (process[j-1]->exponent == process[j]->exponent){
				if(process[j-1]->base > process[j]->base ){
					temp = process[j-1];
					process[j-1] = process[j];
					process[j] = temp;
				}
			}
		}
   }
  //Deletes the temporary process to free up memory
  //delete temp;
}

void welcomeMsg(){
	cout<<"Welcome to Group 14's Processes Execution Simulator!"<<endl;
	cout<<"For this simulation, processors have the following attributes "
	"Speed: 2GHz"<<endl;
	//cout<<"Speed: 2GHz \nMemory:10Mb\n"<<endl;
	cout<<"Let's get started!\n"<<endl;
}

void endMsg(){
	cout<<"Thank you for using our simulator!\n"<<endl;
	cout<<"The files generated by this program for verification are:"<<endl;
	cout<<"processes.txt\ndata.txt\n"<<endl;
	cout<<"Goodbye!"<<endl;
}

void userPrompt(int &numProcs){
	cout<<"How many processors would you like to create?"<<endl;
	cout<<"Enter a value [1-5]:";
	cin>>numProcs;
	
	//Error checker
	while(numProcs<1 || numProcs>5){
		cout<<"\nError! Invalid value detected!"<<endl;
		cout<<"Enter a value [1-10]:";
		cin>>numProcs;
	}
	
}

int main(){
	int numJobs=50;
	int numProcs=1;
	float memTotal=0;
	double time;
	string prompt;
	clock_t t;
	
	//Clears screen
    //system("clear");
    clear();

	//Welcome message
	welcomeMsg();

	//Prompts user for input
	userPrompt(numProcs);
	
	//Creation of processes
	cout<<"\nCreating "<<numJobs <<" processes...";
	c_Proc* process[numJobs];
	for(int i=0;i<numJobs;i++)
		process[i] = new c_Proc(i);
	cout<<numJobs <<" new processes created."<<endl;
	
	//Runs scheduler and clocks
	auto t1 = std::chrono::high_resolution_clock::now();
	cout<<"Running processes...";
	if(simulator(process, numJobs, numProcs, memTotal)){
		cout<<"All processes successfully ran!\n"<<endl;
		auto t2 = std::chrono::high_resolution_clock::now();
		//Outputs time
		time = std::chrono::duration_cast<std::chrono::microseconds>(t2-t1).count();
		time = time/1000;
		cout<<"\nIt took us "<<time;
		cout<<"ms to run all processes\n"<<endl;
	}
	else{
		cout<<"Error! We ran out of memory for the processes"<<endl;
		auto t2 = std::chrono::high_resolution_clock::now();
		//Outputs time
		time = std::chrono::duration_cast<std::chrono::microseconds>(t2-t1).count();
		time = time/1000;
		cout<<"\nIt took us "<<time;
		cout<<"ms to run the processes up to this point.\n"<<endl;
	}
	

	
	//Outputs total memory consumption
	cout<<"Total memory of all processes is ";
	cout<<memTotal/1000000<<"Mb\n"<<endl;
	
	//Displays which processor has which job assigned to it
	//processorOutput();

	//Sends processes info to processes.txt
	processOutput(process,numJobs);

	//Sends memory consumption and total time to data.txt
	simulationOutput(memTotal,time,numJobs,numProcs);
	
	//Program termination
	endMsg();

	return 0;
}
